name: E2E Tests
on:
  push:
    branches:
      - "develop"
      - "feature/**"
      - "fix/**"
      - "test/**"
      - "!staging"
      - "!prod"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Get Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: pnpm vitest
   
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
